### Create
curl -X POST 'http://localhost:65533/posts' \
  --header 'Content-Type: application/json' \
  --data '{
    "title": "Hello",
    "content": "World!"
  }'

### Read
curl -X GET 'http://localhost:65533/posts/${UUID}'